service: Margaret

provider:
  name: aws
  region: eu-west-1
  stage: production
  timeout: 300

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3

resources:
  Resources:
    WebBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: margaret-chat-web
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: [GET, PUT]
              AllowedOrigins: ["*"]
              MaxAge: 31536000
              ExposedHeaders: ['ETag']
        WebsiteConfiguration:
          IndexDocument: index.html
    WebBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref WebBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::margaret-chat-web/*'
