name: App

on:
  push:
    branches:
      - main
    paths:
      - 'Web/**'
      - '.github/workflows/deploy.yml'

jobs:
  Serverless:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install, build, deploy
      run: |
        npm install
        sls deploy --region eu-west-1 --stage production
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: 'public'
    
  Web:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    defaults:
      run:
        working-directory: Web

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Set build numbers
      run: |
        npm install
        npm run build

    - name: Deploy
      run: |
        aws s3 sync ./build s3://margaret-chat-web --metadata-directive REPLACE --cache-control maxage=31536000,public,immutable --exclude "*.html"

        aws s3 sync ./build s3://margaret-chat-web --metadata-directive REPLACE --cache-control s-maxage=604800,max-age=300,public,must-revalidate --exclude "*" --include "*.html"

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: 'public'
  
  Cache:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: 'ubuntu-latest'
    timeout-minutes: 20
    needs: [Serverless, Web]
    steps:

    - name: Invalidate the CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id E1YDL3Q5I7R22A --paths "/" "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
        AWS_REGION: 'eu-west-1'
